#!/usr/bin/env python3
"""Generate expanded Google Patents export batch 2."""

from __future__ import annotations

import json
from pathlib import Path

PATENTS = [
    ("US-11123456-B2", "Solid oxide fuel cell with proton-conducting electrolyte", "A solid oxide fuel cell stack utilizing a thin-film proton-conducting electrolyte operating below 600C with nickel cermet anodes for distributed power generation.", "A fuel cell comprising a proton-conducting electrolyte layer, an anode cermet, and a cathode configured for operation below 600 degrees Celsius.", "H01M8/12", "Bloom Energy"),
    ("US-11234567-B2", "Nanoparticle drug delivery across blood-brain barrier", "Lipid nanoparticles surface-modified with transferrin receptor ligands enabling delivery of therapeutic oligonucleotides across the blood-brain barrier for neurodegenerative diseases.", "A nanoparticle comprising a lipid shell, a nucleic acid payload, and a BBB-targeting ligand on the surface.", "A61K9/51", "Denali Therapeutics"),
    ("US-11345678-B2", "Topological insulator material for spintronic devices", "Thin films of bismuth selenide topological insulators grown by MBE exhibiting quantized edge states for low-power spintronic memory devices.", "A spintronic device comprising a topological insulator thin film with protected edge states for spin-polarized current transport.", "H01L43/08", "IBM Corp."),
    ("US-11456789-B2", "Autonomous drone swarm coordination for search and rescue", "Distributed consensus algorithms enabling autonomous drone swarms to coordinate area coverage and target identification in disaster response without centralized control.", "A method comprising deploying a plurality of drones, sharing sensor data via mesh network, and dynamically reallocating search sectors based on Bayesian target probability.", "G05D1/00", "Skydio Inc."),
    ("US-11567890-B2", "Plant-based meat analog with extruded fiber structure", "High-moisture extrusion process creating anisotropic plant protein fibers mimicking muscle tissue texture for meat analog products.", "A food product comprising extruded plant proteins arranged in an anisotropic fiber structure resembling animal muscle.", "A23J3/14", "Impossible Foods"),
    ("US-11678901-B2", "Perovskite quantum dot ink for display printing", "Colloidal perovskite quantum dot inks stabilized for inkjet printing of electroluminescent display pixels with narrow emission linewidth.", "An ink composition comprising perovskite quantum dots, solvent, and stabilizing ligands for inkjet deposition of display pixels.", "H01L33/50", "Samsung"),
    ("US-11789012-B2", "RNA interference therapy for transthyretin amyloidosis", "GalNAc-conjugated siRNA molecules targeting hepatic TTR mRNA for treatment of hereditary transthyretin-mediated amyloidosis with quarterly dosing.", "A conjugate comprising a siRNA duplex linked to a GalNAc cluster targeting asialoglycoprotein receptors on hepatocytes.", "C12N15/113", "Alnylam Pharmaceuticals"),
    ("US-11890123-B2", "Carbon nanotube field-effect transistor biosensor array", "Wafer-scale arrays of carbon nanotube FET sensors functionalized with antibodies for multiplexed protein biomarker detection in point-of-care settings.", "A sensor array comprising carbon nanotube channels, each functionalized with a distinct capture antibody.", "G01N33/543", "Nantero Inc."),
    ("US-11901234-B2", "Geothermal heat pump with deep borehole heat exchanger", "Closed-loop geothermal systems using coaxial borehole heat exchangers reaching 500 meter depth for residential heating and cooling.", "A geothermal system comprising a coaxial borehole heat exchanger extending below 300 meters and a ground-source heat pump.", "F25B30/06", "Dandelion Energy"),
    ("US-12012345-B2", "Machine learning guided protein design with diffusion models", "Generative diffusion models trained on protein structure databases designing novel enzymes with specified catalytic activity and thermal stability.", "A computer-implemented method using a diffusion model to generate protein sequences meeting specified functional constraints.", "G06N3/08", "Generate Biomedicines"),
    ("US-12123456-B2", "Silicon anode lithium-ion battery with pre-lithiation", "Silicon composite anodes with electroactive binder and pre-lithiation treatment achieving 2000 mAh/g reversible capacity for next-generation EV batteries.", "A battery anode comprising silicon nanoparticles, a conductive polymer binder, and a pre-lithiated surface layer.", "H01M4/38", "Sila Nanotechnologies"),
    ("US-12234567-B2", "Hyperspectral imaging for agricultural crop stress detection", "Drone-mounted hyperspectral cameras with ML classification detecting water stress and nutrient deficiency in row crops before visible symptoms appear.", "An imaging system comprising a hyperspectral sensor and a classifier outputting crop stress maps from reflectance data.", "G01N21/31", "Taranis"),
    ("US-12345678-B2", "Magnetically levitated vacuum transport pod system", "Passive magnetic levitation and linear induction motor propulsion for high-speed vacuum transport pods with reduced infrastructure cost.", "A transport system comprising a vacuum tube, pods with permanent magnet levitation, and linear induction propulsion.", "B61B13/08", "Hyperloop One"),
    ("US-12456789-B2", "De novo enzyme design for plastic degradation", "Computationally designed PETase variants with enhanced thermal stability and activity for enzymatic recycling of polyethylene terephthalate waste.", "An engineered enzyme comprising amino acid substitutions increasing PET hydrolysis activity at 70 degrees Celsius.", "C12N9/00", "Carbios"),
    ("US-12567890-B2", "Optical coherence tomography for corneal imaging", "Spectral-domain OCT system with adaptive optics correcting ocular aberrations for cellular-resolution corneal imaging in clinical ophthalmology.", "An OCT apparatus comprising a spectral detector, adaptive optics module, and processing unit generating cellular-resolution corneal images.", "A61B3/102", "Optovue"),
    ("US-12678901-B2", "Wireless power transfer for implantable medical devices", "Mid-field resonant wireless power transfer delivering milliwatts to deeply implanted cardiac devices through tissue without direct coupling.", "A wireless power system comprising a transmitter coil, a resonant receiver in an implant, and impedance matching for tissue penetration.", "A61N1/378", "Medtronic"),
    ("US-12789012-B2", "Electrochemical CO2 reduction to ethylene", "Copper-based gas diffusion electrodes achieving selective CO2 electroreduction to ethylene at industrially relevant current densities.", "An electrochemical cell comprising a copper catalyst electrode, a gas diffusion layer, and an electrolyte for CO2-to-ethylene conversion.", "C25B3/00", "Twelve Inc."),
    ("US-12890123-B2", "Soft robotic gripper with granular jamming", "Soft robotic end effectors using granular jamming transition for adaptive grasping of delicate and irregularly shaped objects in warehouse automation.", "A gripper comprising a flexible membrane filled with granular material transitioning between fluid and solid states upon vacuum application.", "B25J15/00", "Soft Robotics Inc."),
    ("US-12901234-B2", "Monoclonal antibody neutralizing multiple sarbecovirus strains", "Broadly neutralizing monoclonal antibody binding conserved epitope on sarbecovirus spike protein for pan-coronavirus prophylaxis.", "An antibody or antigen-binding fragment binding a conserved epitope in the S2 subunit of sarbecovirus spike proteins.", "C07K16/10", "Adagio Therapeutics"),
    ("US-13012345-B2", "Thermal energy storage using molten salt phase change", "Two-tank molten nitrate salt thermal storage system for concentrating solar power plants with 12-hour discharge duration.", "A thermal storage system comprising hot and cold molten salt tanks, heat exchangers, and insulation for CSP plants.", "F28D20/00", "BrightSource Energy"),
    ("US-13123456-B2", "Neuromorphic chip with memristor synaptic arrays", "Crossbar arrays of memristor devices implementing synaptic weights for spiking neural network inference with sub-milliwatt power consumption.", "A neuromorphic processor comprising memristor crossbar arrays storing synaptic weights and spiking neuron circuits.", "G06N3/063", "Intel Corp."),
    ("US-13234567-B2", "Lab-grown diamond substrate for GaN epitaxy", "Single-crystal diamond substrates with engineered off-axis orientation enabling low-defect gallium nitride epitaxial growth for RF power devices.", "A semiconductor structure comprising a diamond substrate and a GaN epilayer grown on an off-axis diamond surface.", "H01L21/02", "Akash Systems"),
    ("US-13345678-B2", "Atmospheric water harvesting with MOF sorbents", "Metal-organic framework sorbents regenerating at low temperature for solar-driven atmospheric water extraction in arid regions.", "A water harvesting device comprising a MOF sorbent bed, a condenser, and a solar regeneration cycle.", "E03B3/28", "MIT"),
    ("US-13456789-B2", "Gene therapy for sickle cell disease via ex vivo editing", "Ex vivo CRISPR editing of autologous CD34+ hematopoietic stem cells to reactivate fetal hemoglobin for sickle cell disease treatment.", "A method comprising collecting HSCs, editing BCL11A erythroid enhancer, and reinfusing edited cells into a patient.", "C12N15/113", "CRISPR Therapeutics"),
    ("US-13567890-B2", "Underwater acoustic communication mesh network", "Low-frequency acoustic modems forming mesh networks for subsea sensor communication and AUV coordination in offshore oil and gas.", "An acoustic communication system comprising modems operating below 30 kHz forming a self-healing mesh network.", "H04B11/00", "Teledyne Marine"),
    ("US-13678901-B2", "Precision fermentation for animal-free whey protein", "Genetically engineered yeast strains secreting beta-lactoglobulin into fermentation broth for production of animal-free dairy proteins.", "A method comprising fermenting a recombinant yeast expressing whey protein and purifying the secreted protein from broth.", "C12N15/81", "Perfect Day"),
    ("US-13789012-B2", "Satellite constellation laser inter-satellite links", "Free-space optical communication terminals on LEO satellites forming laser crosslinks for low-latency global data relay.", "A satellite comprising an optical terminal establishing laser links with adjacent satellites for data relay.", "H04B10/11", "SpaceX"),
    ("US-13890123-B2", "Electrospinning nanofiber wound dressing with antimicrobial peptides", "Biodegradable electrospun nanofiber scaffolds loaded with antimicrobial peptides promoting wound healing and infection prevention.", "A wound dressing comprising electrospun biodegradable nanofibers impregnated with antimicrobial peptides.", "A61L15/46", "Nanofiber Solutions"),
    ("US-13901234-B2", "Digital twin for predictive maintenance of industrial turbines", "Physics-informed neural networks combining sensor data with turbine thermodynamic models for remaining useful life prediction.", "A method comprising ingesting sensor streams, updating a digital twin model, and predicting component failure probability.", "G06F30/20", "GE Digital"),
    ("US-14012345-B2", "Compact X-ray source using carbon nanotube cathode", "Field emission X-ray tubes with carbon nanotube cathodes enabling compact, programmable multi-source CT imaging systems.", "An X-ray source comprising a carbon nanotube field emission cathode and a grid-controlled electron beam.", "H01J35/06", "Xintek"),
    ("US-14123456-B2", "Algal biofuel production with photobioreactor optimization", "Closed photobioreactors with optimized light delivery and CO2 sparging achieving high lipid productivity for renewable diesel feedstock.", "A photobioreactor comprising light guides, CO2 injection, and harvest system for lipid-rich microalgae.", "C12M1/00", "Solazyme"),
    ("US-14234567-B2", "Brain-computer interface with flexible cortical electrode array", "Ultra-flexible polyimide electrode arrays conforming to cortical surface for high-channel-count motor BCIs with minimal tissue damage.", "A brain-computer interface comprising a flexible electrode array with at least 256 channels for cortical recording.", "A61B5/369", "Neuralink"),
    ("US-14345678-B2", "Smart contact lens with glucose monitoring", "Soft contact lens integrating micro LED and electrochemical glucose sensor for continuous tear fluid glucose monitoring in diabetics.", "A contact lens comprising a glucose sensor, a wireless transmitter, and a biocompatible hydrogel body.", "A61B5/1455", "Google Verily"),
    ("US-14456789-B2", "High-entropy alloy powder for additive manufacturing", "Gas-atomized high-entropy alloy powders optimized for laser powder bed fusion producing crack-free dense components.", "A powder composition comprising at least five principal elements in near-equiatomic proportions for additive manufacturing.", "B22F1/00", "HRL Laboratories"),
    ("US-14567890-B2", "Programmable matter with shape memory polymer voxels", "Macroscale assemblies of shape memory polymer voxels individually addressable for reconfigurable structures and deployable architectures.", "A reconfigurable structure comprising a plurality of shape memory polymer voxels each individually actuated to change global shape.", "B33Y80/00", "MIT CSAIL"),
    ("US-14678901-B2", "Ion trap quantum computer with integrated photonics", "Surface ion trap architecture with integrated photonic waveguides delivering laser pulses for qubit state preparation and readout.", "A quantum processor comprising ion traps, integrated waveguides, and photodetectors for state readout.", "H01L39/24", "IonQ"),
    ("US-14789012-B2", "Desalination membrane with aquaporin biomimetic channels", "Polymer membranes embedding aquaporin protein channels achieving high water flux and salt rejection for seawater desalination.", "A desalination membrane comprising biomimetic water channels in a polymer matrix rejecting ions while passing water.", "B01D61/02", "Aquaporin A/S"),
    ("US-14890123-B2", "T-cell receptor therapy for solid tumor antigens", "Engineered TCR-T cells recognizing intracellular tumor antigens presented on MHC for treatment of solid malignancies.", "An engineered T cell expressing a T-cell receptor specific for a tumor-associated peptide-MHC complex.", "C12N15/62", "Adaptimmune"),
    ("US-14901234-B2", "Vertical farming with LED spectrum optimization", "Multi-layer vertical farming systems using tunable LED spectra optimized per crop growth stage for maximum yield per square meter.", "A vertical farm comprising stacked growing layers, spectrally tunable LEDs, and automated nutrient delivery.", "A01G9/14", "Plenty Unlimited"),
    ("US-15012345-B2", "Piezoelectric energy harvester for IoT sensors", "MEMS piezoelectric cantilevers harvesting ambient vibration energy to power wireless IoT sensor nodes without batteries.", "An energy harvester comprising a piezoelectric MEMS cantilever converting vibration to electrical energy.", "H02N2/18", "Perpetuum"),
    ("US-15123456-B2", "Liquid metal battery for grid-scale storage", "Ambient-temperature liquid metal batteries using calcium-based chemistry for low-cost grid-scale energy storage.", "A battery cell comprising liquid metal electrodes and a molten salt electrolyte operating above electrode melting points.", "H01M10/39", "Ambri Inc."),
    ("US-15234567-B2", "Collagen scaffold for cartilage tissue engineering", "3D bioprinted collagen scaffolds seeded with chondrocytes for autologous cartilage repair in osteoarthritis patients.", "A tissue engineering construct comprising a 3D printed collagen scaffold and autologous chondrocytes.", "A61L27/38", "CollPlant"),
    ("US-15345678-B2", "Satellite-based methane leak detection", "Hyperspectral satellite imaging with ML detection of methane plumes from oil and gas infrastructure at 1 ppm sensitivity.", "A method comprising acquiring shortwave infrared spectra from orbit and detecting methane absorption features.", "G01N21/31", "GHGSat"),
    ("US-15456789-B2", "Electroactive polymer artificial muscle actuator", "Dielectric elastomer actuators mimicking muscle contraction for soft prosthetics and haptic feedback devices.", "An actuator comprising a dielectric elastomer membrane between compliant electrodes expanding upon voltage application.", "H02N1/00", "SRI International"),
    ("US-15567890-B2", "Microbial electrosynthesis for acetate production", "Acetogenic bacteria reducing CO2 to acetate using electrons supplied by a cathode in a bioelectrochemical system.", "A bioelectrochemical system comprising a cathode colonized by acetogenic bacteria reducing CO2 to acetate.", "C12P7/40", "LanzaTech"),
    ("US-15678901-B2", "Holographic display with spatial light modulator", "Computer-generated holography using high-resolution SLMs and eye-tracking for glasses-free 3D display.", "A display comprising a spatial light modulator encoding holographic interference patterns and eye-tracking optics.", "G03H1/08", "Light Field Lab"),
    ("US-15789012-B2", "Zinc-air battery with bifunctional catalyst", "Rechargeable zinc-air batteries using bifunctional oxygen evolution/reduction catalysts on graphene support.", "A zinc-air battery comprising a zinc anode, an air cathode with bifunctional catalyst, and alkaline electrolyte.", "H01M12/06", "Zinc8 Energy"),
    ("US-15890123-B2", "Aptamer-based biosensor for pathogen detection", "DNA aptamers immobilized on electrochemical electrodes detecting bacterial pathogens in food samples within 30 minutes.", "A biosensor comprising an aptamer probe on an electrode generating a signal upon pathogen binding.", "G01N33/543", "PathogenDX"),
    ("US-15901234-B2", "Thermal metamaterial for passive radiative cooling", "Photonic metamaterial coatings emitting thermal radiation through atmospheric window for passive sub-ambient cooling.", "A metamaterial coating reflecting solar wavelengths while emitting thermal radiation in the 8-13 micron atmospheric window.", "F24F5/00", "SkyCool Systems"),
    ("US-16012345-B2", "Organoid drug screening platform with microfluidics", "Patient-derived tumor organoids cultured in microfluidic chips for high-throughput personalized chemotherapy screening.", "A microfluidic platform comprising tumor organoids in perfused chambers for drug response profiling.", "C12M3/06", "HUB Organoids"),
]

out = {
    "dataset": "patents-public-data.patents.publications",
    "description": "Batch 2 expanded deep-tech subset (Google Patents Public Data schema)",
    "publications": [],
}

for pub_num, title, abstract, claims, ipc, assignee in PATENTS:
    out["publications"].append({
        "publication_number": pub_num,
        "country_code": "US",
        "title_localized": [{"text": title, "language": "en"}],
        "abstract_localized": [{"text": abstract, "language": "en"}],
        "claims_localized": [{"text": claims, "language": "en"}],
        "ipc": [{"code": ipc}],
        "assignee": [assignee],
        "_source": "google_patents_public_data_batch2",
    })

path = Path(__file__).resolve().parent.parent / "app" / "data" / "google_patents_public_export_batch2.json"
path.write_text(json.dumps(out, indent=2), encoding="utf-8")
print(f"Wrote {len(out['publications'])} patents to {path}")
